name: easy_scroll_to_index
description: A new Flutter package support scroll to index for Listview, Gridview and NestedScrollView
homepage: https://github.com/dinhhung1999/easy_scroll_to_index
repository: https://github.com/dinhhung1999/easy_scroll_to_index
issue_tracker: https://github.com/dinhhung1999/easy_scroll_to_index/issues
documentation: https://github.com/dinhhung1999/easy_scroll_to_index

version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

